export const demoCats = [
  {
    id: "luna-demo",
    name: "Luna",
    ageMonths: 14,
    sex: "FEMALE",
    breed: "Domestic Shorthair",
    personality: "Playful, cuddly, window-watcher",
    healthStatus: "Healthy, vaccinated and sterilized",
    vaccinated: true,
    sterilized: true,
    compatibleWithChildren: true,
    compatibleWithCats: true,
    compatibleWithDogs: false,
    location: "Brooklyn, NY",
    description: "Luna is a bright little moonbeam who loves wand toys, sunny naps and gentle people.",
    adoptionStatus: "AVAILABLE",
    photos: [{ url: "https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?auto=format&fit=crop&w=1200&q=80", order: 0 }],
    shelter: { name: "City Whiskers Rescue", city: "Brooklyn", country: "USA" },
  },
  {
    id: "miso-demo",
    name: "Miso",
    ageMonths: 28,
    sex: "MALE",
    breed: "Orange Tabby",
    personality: "Social, goofy, food-motivated",
    healthStatus: "Healthy and vaccinated",
    vaccinated: true,
    sterilized: true,
    compatibleWithChildren: true,
    compatibleWithCats: false,
    compatibleWithDogs: true,
    location: "Jersey City, NJ",
    description: "Miso greets everyone at the door and would love a family that enjoys big cat energy.",
    adoptionStatus: "AVAILABLE",
    photos: [{ url: "https://images.unsplash.com/photo-1574158622682-e40e69881006?auto=format&fit=crop&w=1200&q=80", order: 0 }],
    shelter: { name: "Paws & Purrs Shelter", city: "Jersey City", country: "USA" },
  },
  {
    id: "olive-demo",
    name: "Olive",
    ageMonths: 8,
    sex: "FEMALE",
    breed: "Tuxedo",
    personality: "Curious, gentle, lap apprentice",
    healthStatus: "Recovering well from rescue intake",
    vaccinated: true,
    sterilized: false,
    compatibleWithChildren: false,
    compatibleWithCats: true,
    compatibleWithDogs: false,
    location: "Queens, NY",
    description: "Olive is a quiet sweetheart learning confidence one treat at a time.",
    adoptionStatus: "AVAILABLE",
    photos: [{ url: "https://images.unsplash.com/photo-1592194996308-7b43878e84a6?auto=format&fit=crop&w=1200&q=80", order: 0 }],
    shelter: { name: "Second Chance Cats", city: "Queens", country: "USA" },
  },
];
